// const p = Promise.resolve({id:1});
// p.then(result => console.log(result));

// const p = Promise.reject(new Error("reason for reject..."));
// p.catch(error => console.log(error));